### ISSUE TITLE
Cannot display subtitles when the video is too long

### ISSUE THREAD

**Issue by desireYY** [lexxai/coursera-subtitle-translate-extension#1]
I found that when coursera course videos exceed a certain length, the translated subtitles cannot be displayed. I tested two videos longer than ten minutes, but the translated subtitles could not be displayed. Test case video: https://www.coursera.org/learn/game-design-and-development-1/lecture/oXt3w/unity-editor-overview

**Comment by lexsysko** [comment]
Since translation is an external free service that uses the GET method, it limits the length of GET data that can be sent. 
As far as I remember, my tests show a maximum of 8 KB in modern browsers. 

In other Python projects, I use chunking methods for offline translation.
